<template>
  <LayoutHeader>
    <template #left-header>
      <Breadcrumbs :items="breadcrumbs" />
    </template>
    <template #right-header>
      <div class="flex gap-2 justify-end" v-if="alreadyActions">
        <Dropdown
          :options="[
            {
              group: __('Delete'),
              items: [
                {
                  label: __('Delete post'),
                  icon: 'trash',
                  onClick: () => {
                    showModalDelete = true
                  },
                },
              ],
            },
          ]"
        >
          <Button size="md">
            <template #icon>
              <FeatherIcon name="more-horizontal" class="h-4 w-4" />
            </template>
          </Button>
        </Dropdown>
        <Button
          variant="subtle"
          theme="gray"
          size="md"
          :label="__('Cancel')"
          @click="post.reload()"
          :disabled="!dirty"
        ></Button>
        <Button
          variant="solid"
          theme="blue"
          size="md"
          :label="__('Save')"
          @click="callUpdateDoc"
          :disabled="!dirty"
        ></Button>
      </div>
    </template>
  </LayoutHeader>
  <div class="p-6 overflow-auto">
    <div v-if="msgError" class="p-4 border border-gray-300 rounded-sm mb-4">
      <div class="text-base text-red-600 font-bold mb-2">
        {{ __('An error has occurred') }}:
      </div>
      <ErrorMessage :message="msgError" />
    </div>
    <div v-if="_post" class="p-6 border border-gray-300 rounded-sm mb-4">
      <div>
        <div class="mb-4">
          <h2 class="font-bold text-xl">{{ __('Basic information') }}</h2>
        </div>
        <div class="mb-5">
          <Fields :sections="sections" :data="_post" />
        </div>
      </div>
      <div class="mt-2 mb-5 border-t">
        <div class="my-4">
          <h2 class="font-bold text-xl">SEO</h2>
        </div>
        <div class="mb-5">
          <Fields :sections="sections1" :data="_post" />
        </div>
      </div>
    </div>
    <div v-else class="p-4 border border-gray-300 rounded-sm mb-4">
      <div class="flex justify-center h-screen mt-40 text-gray-700">
        <LoadingIndicator class="h-8 w-8" />
      </div>
    </div>
  </div>
  <Dialog
    :options="{
      title: __('Delete post'),
      actions: [
        {
          label: __('Delete'),
          variant: 'solid',
          theme: 'red',
          onClick: (close) => deleteDoc(close),
        },
      ],
    }"
    v-model="showModalDelete"
  >
    <template v-slot:body-content>
      <div>
        <div>
          {{ __('Are you sure you want to delete the post') }}:
          <b>"{{ _post?.title }}"</b>?
        </div>
        <div class="text-base">
          <p>
            <b class="text-red-600">- {{ __('Cannot be undone.') }}</b>
          </p>
        </div>
      </div>
    </template>
  </Dialog>
</template>

<script setup>
import Fields from '@/components/Fields.vue'
import LayoutHeader from '@/components/LayoutHeader.vue'
import {
  Breadcrumbs,
  ErrorMessage,
  call,
  createResource,
  Dropdown,
} from 'frappe-ui'
import { createToast, errorMessage, warningMessage, validErrApi } from '@/utils'
import { ref, computed, watch } from 'vue'
import { useRouter } from 'vue-router'
import { globalStore } from '@/stores/global'
const { changeLoadingValue } = globalStore()

const router = useRouter()
const props = defineProps({
  postId: {
    type: String,
    required: true,
  },
})
const msgError = ref()
let _post = ref({})
const showModalDelete = ref(false)

const sections = computed(() => {
  return [
    {
      section: 'post-1',
      columns: 1,
      class: 'md:grid-cols-2',
      fields: [
        {
          label: 'Post title',
          mandatory: true,
          name: 'title',
          type: 'data',
          placeholder: 'Enter name',
        },
        {
          label: 'Display post',
          labelInput: 'Show',
          name: 'published',
          type: 'checkbox',
        },
        {
          section: 'post-1-1',
          typeArray: true,
          fields: [
            {
              label: 'Category',
              name: 'category',
              type: 'link',
              placeholder: 'Select category',
              doctype: 'Mbw Blog Category',
              mandatory: true,
            },
            {
              label: 'Tags',
              name: 'tags',
              type: 'multilink',
              placeholder: 'Select tag',
              doctype: 'MBW Blog Tag',
            },
            {
              label: 'Post introduction',
              name: 'blog_intro',
              type: 'textarea',
              placeholder: 'Enter',
              rows: 10,
            },
          ],
        },
        {
          section: 'post-1-2',
          typeArray: true,
          fields: [
            {
              label: 'Publish date (automatically generated by default)',
              name: 'published_on',
              type: 'date',
              placeholder: 'dd/mm/yyyy',
            },
            {
              label: 'Slug (automatically generated by default)',
              name: 'route',
              type: 'data',
              placeholder: 'Enter',
            },

            {
              label: 'Image',
              name: 'upload_file_image',
              type: 'upload_image',
              imgPreview: 'meta_image',
            },
          ],
        },
      ],
    },
    {
      section: 'post-2',
      columns: 1,
      class: 'md:grid-cols-1',
      hideBorder: true,
      fields: [
        {
          label: 'Post content',
          name: 'content',
          type: 'texteditor',
          placeholder: 'Enter',
        },
      ],
    },
  ]
})

const sections1 = computed(() => {
  return [
    {
      section: 'post-3',
      columns: 1,
      class: 'md:grid-cols-2',
      fields: [
        {
          label: 'Meta title',
          name: 'meta_title',
          type: 'data',
          placeholder: 'Enter',
        },
      ],
    },
    {
      section: 'post-4',
      columns: 1,
      class: 'md:grid-cols-2',
      hideBorder: true,
      fields: [
        {
          label: 'Meta keywords',
          name: 'meta_keywords',
          type: 'textarea',
          placeholder: 'Enter',
          rows: 10,
        },
        {
          label: 'Meta description',
          name: 'meta_description',
          type: 'textarea',
          placeholder: 'Enter',
          rows: 10,
        },
      ],
    },
  ]
})

const post = createResource({
  url: 'go1_cms.api.post.get_post',
  params: {
    name: props.postId,
  },
  auto: true,
  transform: (data) => {
    data.tags = data.tags.map((tag) => ({
      ...tag,
      id: tag.name,
      name: tag.tag,
    }))
    data.published = data.published == 1
    data.upload_file_image = null
    _post.value = JSON.parse(JSON.stringify(data))
    return data
  },
  onError: (err) => {
    validErrApi(err, router)
  },
})

// handle allow actions
const alreadyActions = ref(false)
const dirty = computed(() => {
  return JSON.stringify(post.data) !== JSON.stringify(_post.value)
})

watch(dirty, (val) => {
  alreadyActions.value = true
})

// update doc
async function callUpdateDoc() {
  msgError.value = null
  let _post_cp = { ..._post.value }

  if (JSON.stringify(post.data) == JSON.stringify(_post_cp)) {
    warningMessage(__('No changes in document'))
    return
  }

  if (!_post_cp.title) {
    errorMessage(__('Post title') + ' ' + __('cannot be empty'))
    return
  }
  if (!_post_cp.category) {
    errorMessage(__('Category') + ' ' + __('cannot be empty'))
    return
  }

  changeLoadingValue(true, __('Saving...'))
  try {
    if (_post.value['upload_file_image']) {
      let headers = { Accept: 'application/json' }
      if (window.csrf_token && window.csrf_token !== '{{ csrf_token }}') {
        headers['X-Frappe-CSRF-Token'] = window.csrf_token
      }

      let imgForm = new FormData()
      imgForm.append(
        'file',
        _post.value['upload_file_image'],
        _post.value['upload_file_image'].name,
      )
      imgForm.append('is_private', 0)
      imgForm.append('doctype', 'Mbw Blog Post')
      imgForm.append('fieldname', 'meta_image')
      imgForm.append('docname', props.postId)
      imgForm.append('file_url_old', _post.value.meta_image)

      await fetch('/api/method/go1_cms.api.handler_file.upload_file', {
        headers: headers,
        method: 'POST',
        body: imgForm,
      })
        .then((res) => res.json())
        .then((data) => {
          if (data.message) {
            // update image doc
            _post.value['meta_image'] = data.message.file_url
          }
        })
        .catch((err) => {
          msgError.value = err.messages.join(', ')
        })
    }

    const docUpdate = await call('go1_cms.api.post.update_post', {
      data: { ..._post.value },
    })

    if (docUpdate.name) {
      post.reload()

      createToast({
        title: __('Saved'),
        icon: 'check',
        iconClasses: 'text-green-600',
      })
    }
  } catch (err) {
    validErrApi(err, router)
    if (err.messages && err.messages.length) {
      msgError.value = err.messages.join(', ')
      errorMessage(__('An error has occurred'), err.messages.join(', '))
    } else {
      errorMessage(__('An error has occurred'), err)
    }
  }
  changeLoadingValue(false)
}

// delete doc
async function deleteDoc(close) {
  changeLoadingValue(true, __('Deleting...'))
  try {
    await call('go1_cms.api.post.delete_post', {
      name: props.postId,
    }).then(() => {
      createToast({
        title: __('Deleted'),
        icon: 'check',
        iconClasses: 'text-green-600',
      })
      close()
      router.push({
        name: 'Posts',
      })
    })
  } catch (err) {
    validErrApi(err, router)
    if (err.messages && err.messages.length) {
      msgError.value = err.messages.join(', ')
      errorMessage(__('An error has occurred'), err.messages.join(', '))
    } else {
      errorMessage(__('An error has occurred'), err)
    }
  }
  changeLoadingValue(false)
}

// breadcrumbs
const breadcrumbs = computed(() => {
  let items = [{ label: __('Post management'), route: { name: 'Posts' } }]
  items.push({
    label: post.data?.title,
    route: {},
  })
  return items
})
</script>
