<template>
  <svg
    version="1.1"
    id="Layer_1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    viewBox="0 0 60 60"
    enable-background="new 0 0 60 60"
    xml:space="preserve"
    fill="currentColor"
    transform="matrix(1, 0, 0, 1, 0, 0)"
  >
    <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
    <g
      id="SVGRepo_tracerCarrier"
      stroke-linecap="round"
      stroke-linejoin="round"
    ></g>
    <g id="SVGRepo_iconCarrier">
      <polyline
        fill="none"
        stroke="currentColor"
        stroke-width="3"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-miterlimit="10"
        points=" 32.594,13.253 2,13.253 2,53.078 49.88,53.078 49.88,30.414 "
      ></polyline>
      <g>
        <line
          fill="none"
          stroke="currentColor"
          stroke-width="3"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-miterlimit="10"
          x1="49.88"
          y1="4.633"
          x2="49.88"
          y2="21.873"
        ></line>
        <line
          fill="none"
          stroke="currentColor"
          stroke-width="3"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-miterlimit="10"
          x1="58.5"
          y1="13.253"
          x2="41.26"
          y2="13.253"
        ></line>
      </g>
      <g>
        <line
          fill="none"
          stroke="currentColor"
          stroke-width="3"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-miterlimit="10"
          x1="12.235"
          y1="28.077"
          x2="31.87"
          y2="28.077"
        ></line>
        <line
          fill="none"
          stroke="currentColor"
          stroke-width="3"
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-miterlimit="10"
          x1="12.235"
          y1="38.254"
          x2="39.645"
          y2="38.254"
        ></line>
      </g>
    </g>
  </svg>
</template>
